version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps):"
    labels:
      - dependencies
      - npm
    open-pull-requests-limit: 10
    groups:
      npm-dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      npm-prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "chore(deps):"
    labels:
      - dependencies
      - github-actions
