name: Dependabot Auto-merge (Cron)

on:
  schedule:
    # Run at 00:49, 08:49, and 16:49 UTC
    - cron: '49 0,8,16 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-aged-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: cmiic/dependabot-automation/cron@473279c6de28189812f4913a62a5feae497bbbba # v1.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
