name: Dependabot Auto-merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: cmiic/dependabot-automation/merge@5ed389108eab8ee3ec9a1ce78f91405fcd13f166 # v1.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
