name: Dependabot Auto-merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: cmiic/dependabot-automation/merge@92c07a205db298afe96d460597a90060f084b5eb # v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
