name: Dependabot Auto-merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: cmiic/dependabot-automation/merge@e371deee6efcd7b2cb3eb8b059286705118cd4b0 # v1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
