name: Dependabot Auto-merge (Cron)

on:
  schedule:
    # Run at 00:49, 08:49, and 16:49 UTC
    - cron: '49 0,8,16 * * *'
  workflow_dispatch: {}

permissions:
  contents: write
  issues: read
  pull-requests: write

jobs:
  check-aged-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: cmiic/dependabot-automation/cron@92c07a205db298afe96d460597a90060f084b5eb # v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
